DROP TABLE BOOK CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE ORDERPRODUCT CASCADE CONSTRAINTS;      
DROP TABLE PUBLISHER CASCADE CONSTRAINTS;
DROP TABLE CLIENT CASCADE CONSTRAINTS;
DROP TABLE BOOKSALE CASCADE CONSTRAINTS;