CREATE SEQUENCE owner_sequence INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE NOORDER;

CREATE SEQUENCE car_sequence INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE NOORDER;

CREATE SEQUENCE member_sequence INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCYCLE NOCACHE NOORDER;

ALTER SEQUENCE member_sequence INCREMENT BY 50;
ALTER SEQUENCE owner_sequence INCREMENT BY 50;
ALTER SEQUENCE car_sequence INCREMENT BY 50;

DROP SEQUENCE owner_sequence;
DROP SEQUENCE car_sequence;
DROP SEQUENCE member_sequence;