--------------------------------------------------------
--  File created - Wednesday-August-13-2025   
--------------------------------------------------------
--  DDL for Table PIVOTTEST
--------------------------------------------------------

  CREATE TABLE "BLUENYANG"."PIVOTTEST" 
   (	"SINGER" VARCHAR2(10 BYTE), 
	"SEASON" VARCHAR2(10 BYTE), 
	"AMOUNT" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BLUENYANG.PIVOTTEST
SET DEFINE OFF;
Insert into BLUENYANG.PIVOTTEST (SINGER,SEASON,AMOUNT) values ('김범수','겨울',10);
Insert into BLUENYANG.PIVOTTEST (SINGER,SEASON,AMOUNT) values ('윤종신','여름',15);
Insert into BLUENYANG.PIVOTTEST (SINGER,SEASON,AMOUNT) values ('김범수','가을',25);
Insert into BLUENYANG.PIVOTTEST (SINGER,SEASON,AMOUNT) values ('김범수','봄',3);
Insert into BLUENYANG.PIVOTTEST (SINGER,SEASON,AMOUNT) values ('김범수','봄',37);
Insert into BLUENYANG.PIVOTTEST (SINGER,SEASON,AMOUNT) values ('윤종신','가을',40);
Insert into BLUENYANG.PIVOTTEST (SINGER,SEASON,AMOUNT) values ('김범수','여름',14);
Insert into BLUENYANG.PIVOTTEST (SINGER,SEASON,AMOUNT) values ('김범수','겨울',22);
Insert into BLUENYANG.PIVOTTEST (SINGER,SEASON,AMOUNT) values ('윤종신','여름',64);
COMMIT;
