spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: greeting_route
              uri: http://localhost:8081
              predicates:
                - Path=/greeting/**

            - id: posts_route
              uri: http://localhost:8081
              predicates:
                - Path=/posts/**

            - id: comments_route
              uri: http://localhost:8082
              predicates:
                - Path=/comments/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080
