/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductProductListRouteImport } from './routes/product/productList'
import { Route as ProductProductDetailPrdNoRouteImport } from './routes/product/productDetail/$prdNo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductListRoute = ProductProductListRouteImport.update({
  id: '/product/productList',
  path: '/product/productList',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductDetailPrdNoRoute =
  ProductProductDetailPrdNoRouteImport.update({
    id: '/product/productDetail/$prdNo',
    path: '/product/productDetail/$prdNo',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/product/productList': typeof ProductProductListRoute
  '/product/productDetail/$prdNo': typeof ProductProductDetailPrdNoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product/productList': typeof ProductProductListRoute
  '/product/productDetail/$prdNo': typeof ProductProductDetailPrdNoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/product/productList': typeof ProductProductListRoute
  '/product/productDetail/$prdNo': typeof ProductProductDetailPrdNoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/product/productList' | '/product/productDetail/$prdNo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/product/productList' | '/product/productDetail/$prdNo'
  id:
    | '__root__'
    | '/'
    | '/product/productList'
    | '/product/productDetail/$prdNo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductProductListRoute: typeof ProductProductListRoute
  ProductProductDetailPrdNoRoute: typeof ProductProductDetailPrdNoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/productList': {
      id: '/product/productList'
      path: '/product/productList'
      fullPath: '/product/productList'
      preLoaderRoute: typeof ProductProductListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/productDetail/$prdNo': {
      id: '/product/productDetail/$prdNo'
      path: '/product/productDetail/$prdNo'
      fullPath: '/product/productDetail/$prdNo'
      preLoaderRoute: typeof ProductProductDetailPrdNoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductProductListRoute: ProductProductListRoute,
  ProductProductDetailPrdNoRoute: ProductProductDetailPrdNoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
